version: 2
jobs:
  build:
    docker:
    - image: circleci/node:8-browsers
    steps:
    - add-ssh-keys:
        fingerprints:
        - "be:53:06:90:d4:51:ec:d1:ae:21:0f:c9:73:81:2f:c7"
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package-lock.json" }}
    - run:
        name: Install deps
        command: make setup
    - save_cache:
        paths:
        - node_modules
        key: v1-dependencies-{{ checksum "package-lock.json" }}
    - run: 
        name: Build
        command: make build
    - deploy:
        name: Deploy to GitHub Pages
        command: |
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            make cache_bust
            make prep_branch
            make publish_branch
          fi
workflows:
  version: 2
  deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
